#! /usr/bin/env python
# MageSane is a sql dump sanitizer for Magento aimed to speed up database imports and reduce filesystem footprints
#
# we want to rebuild the file line per line, leaving out lines with blacklisted words or phrases like 'insert' and '
# log_table'. This way, the resulting dump will only have the data we really need to develop, instead of everything
# in the world. There's truncate scripts floating around, but that takes a ton of time to run and blows up disk space

import sys
import configparser

config = configparser.ConfigParser()
config.read('magesane.ini')
#print(config.sections())
ignore_statements = config['ignore']['statements'].split(',')
ignore_statement_blacklist = config['ignore']['blacklist'].split(',')
ignore_entirely_blacklist = config['ignore']['entirely'].split(',')

if sys.stdin.isatty():
    fileobject = open(sys.argv[1])
else:
    fileobject = sys.stdin.readlines()

for line in fileobject:
    if not [i for i, x in enumerate(ignore_entirely_blacklist) if x in line[0:20]]:
        if not [i for i, x in enumerate(ignore_statements) if x in line[0:20]]:
            print(line)
        else:
            if not [i for i, x in enumerate(ignore_statement_blacklist) if x in line[0:40]]:
                print(line)